### ISSUE TITLE
Device role rights and /devices/me

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#10]
There are two issues when listing devices using `/devices/` endpoint using a device token:
1. All devices that belong to the account are listed. I think this is not the expected behaviour using a device token, and can even be considered a theoretical security risk. We should either **a.** remove device role from this endpoint, **b.** return a list with a single element, the device itself.
2. There is no way to access device info without having device id, I think it should be sufficent to store device token on the devices and not the redundant device id. A `devices/me` endpoint could be used to resolve this. Approach **b** from 1. would also be an option, but I think it is cleaner to implement this endpoint in both cases.

Any thoughts?

**Comment by nevets963** [comment]
Hi Ali, I'm trying to understand this better. Are you calling this API endpoint? /accounts/:accountId/devices or /devices? Because those requests are auth'ed using the token I don't understand the security risk?

It looks like there is an endpoint /devices/{device_id} - does that not return what you want?

**Comment by arkocal** [comment]
Hi Steven,
Yes those endpoints are authorized with a token, but i think a device token should not be authorized to list all devices connected to an account.
The /device/device_id endpoint requires a device_id, in same cases i

**Comment by nevets963** [comment]
Thats a good idea. At least in the event if the device token is comprised, the rest of the account and less prone to being comprised. The negative here is if a device actually wants to know about the other devices in the system, this becomes a limiting factor. I.e. you have 1 device reading the temp and another that is attached a screen or something. Device 1 maybe want to trigger an actuation on Device 2 (without having the cloud trigger the actuation).

**Comment by wagmarcel** [comment]
We could also restrict it to subgroups. E.g. to devices which have a common Gateway (in contrast to all devices in an account). Then we can group the devices which need to know each other by defining the same gateway field.
The admin can then configure it both ways: Either grouping devices or assign different GW IDs to  all devices to isolate them.
Nevertheless, in our security concept, we cannot/should not fine-tune access (either grant or deny). So we would need an additional endpoint if we want to provide e.g. only the gateway data to the device. Or we can make it a parameter in the /devices/me endpoint that the device can request info about their peers with the same GW ID, if they want.
Granting/Denying devices access to the whole devices list is luckily a simple change in the security mapping. So I think this can be configured very easy if need be.
But e.g. with the IoT-Agent the device is typically creating its ID/Name and stores it. Therefore the feature we are talking about is a good add-on but, IMHO, not having a high priority at this time.

**Comment by arkocal** [comment]
@oguzcankirmemis It is probably for the best from a security viewpoint that the devices can not do anything concerning other devices. We should have a discussion on which endpoints to remove permissions from, and eventually new endpoints for devices to get information about themselves.
