### ISSUE TITLE
JWT Token Verification

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/oisp-frontend#115]
There are multiple issues with the way the JWT tokens are verified

1. The jsjwt library in use is far outdated and should be updated (even while no known vulnerabilitis
exist in that version)

2. The algorithm used for signing the messages is currently RSA 256
it is recomended to switch instead to HS256 or even better HS512
this will slightly increase performance during runtime and will save the keypair generation in the
setup/bootup

3. The set up supportedAlg in public-interface/lib/security/config/index.js has to contain _only_ the algorithm choosen to sign the key (i.e. as suggested HS512)

**Comment by oguzcankirmemis** [comment]
Authorization is moved to keycloak, closing.
