### ISSUE TITLE
CryptoUtils weaknesses

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/oisp-frontend#116]
It is recomended to switch the digest algorithm of the PBKDF2 algorithm
to "at least SHA2-256 or SHA3-256" 
https://crypto.stackexchange.com/questions/47517/is-pbkdf2-rfc-2898-broken-because-sha1-is-broken
so this requires editing the "hash" (bad naming) function int file public-interface/lib/cryptoUtils.js

Further the function "hashData" is utelizing "sha1" as hashing function which is considered 
broken and should not be used any more!
Since the function is luckily not used in the code, it should be removed completely

**Comment by oguzcankirmemis** [comment]
Fixed with keycloak integration, closing.
