### ISSUE TITLE
authorization.js deceptive variable names

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/oisp-frontend#117]
in public-interfaces/lib/security/authorization.js the expiry timings are stored 
in milliseconds (js Date()) but the containing variables are indicating a second scheme
This can easily lead to future implementation errors with drastic consequences.

Further:
The function getTokenInfo contains the following piece of code:
```
var expireDate = new Date(payload.exp);

        if(new Date() > expireDate){
            callback();
        } else {
        	var timestamp = expireDate.getTime();
        	payload.exp = timestamp; //TODO
```

This appears like semantic (and performance) clutter and should be reworked
Overall the whole function seems to violate multiple style guidelines and is inconsistently formated

**Comment by oguzcankirmemis** [comment]
closed with #190
