### ISSUE TITLE
CRITICAL SQL injection

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/oisp-frontend#121]
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/37eeed99b2fdd4fcfeb43d6d5987aa5e03542884/public-interface/iot-entities/postgresql/devices.js#L344

This line allows for a complete breach into the postgresql database by appending
a string that was not properly sanatized.
For escaping sql attacks the queryHelper.js was used.
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/develop/public-interface/iot-entities/postgresql/helpers/queryHelper.js

It is highly recomended to completely remove the queryHelper.js from the project
and rewrite all then failing sql requests using the proper buildup syntax of node sequelize.

The same issue appears in countByCriteria()
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/37eeed99b2fdd4fcfeb43d6d5987aa5e03542884/public-interface/iot-entities/postgresql/devices.js#L373

Sequelize should **NEVER** by used with raw strings in this project

**Comment by maxdos64** [comment]
After completion of this fix there is also the need to evaluate the file 
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/develop/public-interface/lib/schema-validator/schemas/device.json

As it contains at multiple positions the value type "any" in the scheme
This is potentially dangerous when using node sequelize -> lists as input could produce unexpected results

**Comment by oguzcankirmemis** [comment]
Postgres refactoring is completed #138, #141, #154, will open a new issue for the schema, closing.
