### ISSUE TITLE
Database Table Changes

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/oisp-frontend#128]
Apart from the naming convention and some field changes, some other breaking changes we are considering to do are:

- Remove the table 'deviceComponentsExportMissingDays'
- Remove the 'provider' field in users
- Create a new table userAttributes for the users
- Create a new table accountAttributes
- Create a new table accountSettings

**Comment by oguzcankirmemis** [comment]
@wagmarcel, regarding the ['provider'](https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/5e2e26c77a27bf13742d0296f746c175e9167de1/public-interface/iot-entities/postgresql/models/users.js#L50) field, I have a question. The purpose of this field is to actually enable the logins into the system via 3rd party apps (like google, facebook or github), when this provider field is set, a verification email will not be sent to the user and user will be able to login using this functionality. Since we are also considering to remove these login methods (#118), I assume we can remove this safely right? Because if not, obviously this field needs to stay.

**Comment by oguzcankirmemis** [comment]
Another dependency that we have to consider is, we create some pre-defined functions at database creation in postgres, to use these later in frontend. For [example](https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/ac9a5aeb6bd1d01022d48cb67f98b389a54aacfb/public-interface/deploy/postgres/base/V00.00.06_00__create_account.sql#L17) we create a function 'dashboard.create_account' to create accounts, and we use this function later in frontend at [here](https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/ac9a5aeb6bd1d01022d48cb67f98b389a54aacfb/public-interface/iot-entities/postgresql/accounts.js#L29). Since we want to remove all these postgres scripts to reduce dependency between modules (we also want to remove it to prevent usage of raw queries in order to be more secure), we will have to rewrite most part of this. I am afraid this will take some time if we truly want to remove these scripts, and only depend on sequelize itself.

**Comment by oguzcankirmemis** [comment]
@wagmarcel, another question is that the fields such as 'max_data_retention' or 'health_time_period' actually appear on the dashboard at account settings. They can't be changed or edited though, so I suppose we will also have to delete these from the dashboard after removing them at postgres/sequelize?

**Comment by arkocal** [comment]
@oguzcankirmemis Did the PR solve this issue? Please close if this is the case.

**Comment by oguzcankirmemis** [comment]
Done after #154, closing.
