### ISSUE TITLE
Postgres configuration should not be hardcoded

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#139]
I believe this bit was forgotten after testing

This was introduced by e385c517e8a50d1d4e3d0464c7c9f67b9331a4a1, see my comment on the PR.

**Comment by oguzcankirmemis** [comment]
This is hardcoded in the config file because this user should only be used by frontend as application user. The problem with kubernetes does not depend on this, see #141, closing...
