### ISSUE TITLE
Why is the wait-for-heartbeat.js script is only exiting when consumer exists?

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#144]
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/2e7f82f53f68ce0056c1428ccff9e05644ad45bb/public-interface/scripts/wait-for-heartbeat.js#L74

@oguzcankirmemis I am still experiencing the "cannot get Kafka offset" hanging of frontend. Either it is not exited correctly at this position because of the condition or the later handling is not leading to the process to exit. please take a look.

**Comment by oguzcankirmemis** [comment]
Apparently, the close function of kafka-consumer accepts a callback, and killing the process before it can close has caused some instability. When the consumer does not exit it was also exiting but with a wrong status code so thank you for pointing that out. I have fixed the issue at #145.

**Comment by oguzcankirmemis** [comment]
Fixed after #145, closing.
