### ISSUE TITLE
True boolean values cannot be submitted.

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#162]
The following works:
```
{"on": 1570008961512, "accountId": "3824f4b4-f689-4568-8ffa-45d0b5a119dd", "data": [{"componentId": "f95f6502-ec48-49df-94fb-d0175088afaa", "value": "1", "on": 1570008950767}]}
```
(see `value: "1"`)

But this does not:
```
{"on": 1570008961512, "accountId": "3824f4b4-f689-4568-8ffa-45d0b5a119dd", "data": [{"componentId": "f95f6502-ec48-49df-94fb-d0175088afaa", "value": true, "on": 1570008950767}]}
```
even though it is valid according to the documentation, the backend cannot handle this, and a `6506` is thrown. In such cases, frontend should perform the conversation. 
I am also skeptical whether it is right to allow `"1"` and `"0"` for boolean values. Do we have any good reason for this?

**Comment by oguzcankirmemis** [comment]
Solved after #165, closing.
