### ISSUE TITLE
Device login provokes internal server error

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#239]
Steps to reproduce (using python sdk):
````python
device = account.create_device("device1", "device1")
token = device.activate()
new_login_device = client.get_device("device1", token)
```` 
*Expected:* Successful login.
*Returns:* HTTP Code 500, Internal Server Error.

This might also be a bug in the SDK, but if the SDK is doing something wrong, frontend should return a meaningful denial message.

**Comment by arkocal** [comment]
Assigned @MericFeyz to observe the workflow and possibly review changes.

**Comment by MericFeyz** [comment]
The server returns a HTTP code of 500 when the given token is invalid.
