### ISSUE TITLE
Frontend crashing in E2E test when Kafka not ready

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#64]

**Comment by oguzcankirmemis** [comment]
It seems like this issue is resolved after [#91](https://github.com/Open-IoT-Service-Platform/platform-launcher/pull/91), will investigate further just in case

**Comment by wagmarcel** [comment]
If frontend crashes when kafka is not ready it is a bug. It might be less likely to happen with the PR. Still we need to make frontend robust wrt this error

**Comment by wagmarcel** [comment]
cannot be reproduced after #91. Closing for now.
