### ISSUE TITLE
GPS coordinates of devices not shown in GUI

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#69]
With new v1.0.4beta release, the GPS coordinates of the devices can be changed but is not displayed in GUI.
Reproduce:
*create device in GUI
*Add GPS coordinates
*reload device

**Comment by wagmarcel** [comment]
Another one which is related: When I add a device through iot-admin and try to add information other than GPS angular returns the error "Cannot read property 'latitude' of undefined"

**Comment by oguzcankirmemis** [comment]
This was fixed at #70 , closing.
