### ISSUE TITLE
Should we commit the package-lock.json?

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/oisp-frontend#73]
After installing the modules with npm, package-lock.json is created and the npm warns that this file should be committed. I know the file is actually big (12.000 lines aproximately for our case),and it could cause a lot of noise or conflict when seeing the diff, but I think we still should commit this file. Because this file guarantees that npm installs the exact same packages, also improves the installation process. It also helps to use npm audit, which searchs for security holes in the tree and tries to fix them if they exist.

So my question would be, should we include this file or not?

**Comment by wagmarcel** [comment]
Good point. I think this should be done on master for the more stable and long term pre-releases. On develop I am not sure whether this brings more problems than benefit.

**Comment by arkocal** [comment]
I think we all agree on @wagmarcel 's suggestion, closing the issue.
