### ISSUE TITLE
Authorization: Why is the user token checked each time? It is only valid for 1hr and should be trusted.

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#83]
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/20f51daa6511218ee1d9c6a5f51e0c9a961c0469/public-interface/lib/security/authorization.js#L110

Shows that, in case the token is not a device token, i.e. a user token, the account list is looked up in the database and compared with the accounts in the token. Is this really needed?
On the other hand, it is not happening very often because bulk of requests should come from devices.
We need to agree on something.

**Comment by arkocal** [comment]
Is not this necessary to disable deleted accounts?
I think in general we should not be optimizing account level stuff unless it becomes necessary or is obviously a bug.
