### ISSUE TITLE
Frontend sometimes returns 404 for existing devices

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#88]
When running tests with more requests, frontend sometimes returns `404` for devices, which are registered in the DB, and are returned from the `account/devices` endpoint. When this happens once, it happens for all consequent requests, until the device is reactivated.

To reproduce, it is enough to spawn a process that makes lots of requests, it takes less than a minute until the first device fails. I was not able to generate a simpler case, I suspect this might be a probabilistic issue, as it tends to happen more often and quickly when the system is under heavy load.

**Comment by wagmarcel** [comment]
@arkocal Does it happen after the recent changes in data-submission or was it observed before as well?

**Comment by arkocal** [comment]
I am not sure, but I believe it was observed before as well.

**Comment by arkocal** [comment]
[error_log.txt](https://github.com/Open-IoT-Service-Platform/oisp-frontend/files/2802533/error_log.txt)
Here is the log, grepped for error. At the end there are errors due to too many samples accumulating in the client, the beginning should be rather interesting. Not all requests to the same device fail btw.

**Comment by wagmarcel** [comment]
OK - this might be intended behavior. Partially this has been introduced with the new submit data behavior: If not all components are registered, then data is sent only to the registered one (as indicated in the error message). The return code 404 with code 6402 means that not all components are registered and sender should check. (Data for valid components are stored and not lost).
I suspect that the registration of one component failed (and is not repeated in the setup). Then evey attempt to send data which contains this component will create this error message.

**Comment by arkocal** [comment]
I do not think this is the issue, because the devices in the [current setup](https://github.com/Open-IoT-Service-Platform/oisp-k8s/blob/f30ac812e515afabd4769519eb87c43626876d12/locust/locustfile.py#L98) have a single component only, which does work for a while, and even after the first error sometimes keeps working. Apart from that, the setup fails and the user is taken out of the pool autmatically if the `on_start` function in the link fails.

**Comment by oguzcankirmemis** [comment]
Does the test try to send the whole data again even if only a part of it fails? I do not think this would be the problem on the frontend side, but depending on the error log you sent, I wanted to find an explanation about the increasing size of the "only following components could be sent" array. (the size actually represents how much data you sent, for every data, component id of that data is added to this array) If this is not the tests doing, then we have a more serious problem here.

**Comment by arkocal** [comment]
Yes that's actually the case. The problem is not the increasing size, but that data for an existing component is rejected.

**Comment by wagmarcel** [comment]
ok. yes I see it. This is most likely a bug in the new submit component I will take a look.

**Comment by arkocal** [comment]
#92 closes this.

Apparently, this was not related to components not being found, but a failed value check results in a 404 instead of a 400.
