### ISSUE TITLE
Admin tool does not return with error on failure

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-frontend#91]
When an admin operation like `node admin resetDB` fails, the process should return a non-zero return code.

This is relevant, because admin tool is likely to be used as a [kubernetes job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) and return code of the process is the best way of seeing whether a job run succesfully.

**Comment by oguzcankirmemis** [comment]
Closed by #96.
